services:
  db:
    image: mysql:8.0
    container_name: crm_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_secure_password
      MYSQL_DATABASE: crm_warehouse
      MYSQL_USER: crm_user
      MYSQL_PASSWORD: crm_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "crm_user", "-pI_LOV_CRM_PASSWORD"]
      timeout: 5s
      retries: 5
      start_period: 10s

  web:
    build: .
    container_name: crm_flask_app
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data: